### ISSUE TITLE
更新时错误

### ISSUE THREAD

**Issue by terryCityu** [mindoc-org/mindoc#821]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
mindoc_windows_amd64 v2.0

2. 你当前使用的是什么操作系统?
server 2012r2

3. 你是如何操作的？
按照教程覆盖文件后执行install命令

4. 你期望得到什么结果?
正常更新

5. 当前遇到的是什么结果?
出现如下错误，确认conf/lang/内存在en-us.ini和zh-cn.ini

panic: initialize locale error: open conf/lang/.ini: The system cannot find the
file specified.

goroutine 1 [running]:
github.com/mindoc-org/mindoc/commands.initialization()
        C:/gopath/src/github.com/mindoc-org/mindoc/commands/install.go:108 +0x70
5
github.com/mindoc-org/mindoc/commands.Install()
        C:/gopath/src/github.com/mindoc-org/mindoc/commands/install.go:27 +0x78
github.com/mindoc-org/mindoc/commands.RegisterCommand()
        C:/gopath/src/github.com/mindoc-org/mindoc/commands/command.go:202 +0x8b

main.main()
        C:/gopath/src/github.com/mindoc-org/mindoc/main.go:29 +0xde

**Comment by gsw945** [comment]
请确认conf目录下lang目录是否存在，这个是国际化添加的，根据你目前的报错，加上就OK了。
可以直接在github或者你下载的压缩包内复制
